### PR TITLE
Add Pins Method Group 

### PR DESCRIPTION
**Pull request by wudmer**
closes: #114

### CODE REVIEW

**Comment by MarvinSchramm** [comment]
Very nice we will look at this today :)

**Comment by BenDenger** [comment]
also closes: #117, #116, #115

**Comment by BenDenger** [comment]
Hello @wudmer are you doing this to solve hacktoberfest issues? If so, please comment on the issues #117, #116, #115 so we can assign you. The issue #114 does not have the hacktoberfest label and you solved all issues in this Pull Request.

**Comment by wudmer** [comment]
@BenDenger Hi, yes. Hacktoberfest labels are optional and only PR counts. 

>  you solved all issues in this Pull Request.
I'm fine with that. I would rather solve another issue than split this PR

**Comment by MarvinSchramm** [comment]
Thank you very much for your Contribution @wudmer

**Pull request merged**
